// Code generated by sql2gorm. DO NOT EDIT.
package models

import (
	"database/sql"
)

type Customer struct {
	CustomerID  int          `gorm:"column:customer_id;type:int(11);primary_key;AUTO_INCREMENT"`
	FirstName   string       `gorm:"column:first_name;type:varchar(255);NOT NULL"`
	LastName    string       `gorm:"column:last_name;type:varchar(255);NOT NULL"`
	Email       string       `gorm:"column:email;type:varchar(255);NOT NULL"`
	PhoneNumber string       `gorm:"column:phone_number;type:varchar(20)"`
	Address     string       `gorm:"column:address;type:varchar(255)"`
	Password    string       `gorm:"column:password;type:varchar(255);NOT NULL"`
	CreatedAt   sql.NullTime `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP"`
	UpdatedAt   sql.NullTime `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP"`
}

func (m *Customer) TableName() string {
	return "customer"
}

